server:
  port: 9090

spring:
  application:
    name: KTM

  datasource:
#    force injection of UTC per db via spring config
    url: jdbc:mysql://localhost:3306/ktm?serverTimezone=UTC
    username: root
    password: secret123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      DDL = Data Definition Language (DDL = CREATE, ALTER, DROP tables)
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: true
#    Dialect = the way a database “speaks” SQL
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    time-zone: UTC

logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 3MB
      max-history: 3
  level:
    root: INFO
    org.springframework: WARN
    com.yourpackage: DEBUG


